name: FastAPI CI/CD Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Tests with Pytest
        run: pytest

  deploy:
    name: Deploy to AWS EC2
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Private Key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: SSH into EC2 and Deploy
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${EC2_IP} << 'EOF'
            # Update system packages
            sudo apt update -y
            sudo apt install -y docker.io

            # Ensure Docker service is running
            sudo systemctl enable docker
            sudo systemctl restart docker

            # Remove old app directory
            sudo rm -rf /home/ubuntu/app

            # Clone the latest code from GitHub
            git clone https://github.com/johnafariogun/test /home/${EC2_USER}/app
            cd /home/ubuntu/app

            # Stop & remove the old container if it exists
            sudo docker stop fastapi-nginx || true
            sudo docker rm fastapi-nginx || true

            # Build the new Docker image
            sudo docker build -t fastapi-nginx:latest .

            # Run the new container (expose ports for future HTTPS setup)
            sudo docker run -d -p 80:80 --name fastapi-nginx fastapi-nginx:latest

            # Verify Deployment (Optional)
            curl -i 127.0.0.1:80/docs
          EOF

      - name: Clean up SSH Key
        if: always()
        run: rm -f private_key
